"""empty message

Revision ID: 14859d8c3f20
Revises: 3730d5f165c1
Create Date: 2019-12-07 12:26:12.905901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14859d8c3f20'
down_revision = '3730d5f165c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('re_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_re_comment_content'), 're_comment', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_re_comment_content'), table_name='re_comment')
    op.drop_table('re_comment')
    # ### end Alembic commands ###
